package net.minestom.server;

import net.minestom.server.utils.MajorMinorVersion;

/**
 * AUTOGENERATED by ConstantsGenerator
 */
interface MinecraftConstants {
    String VERSION_NAME = "25w31a";

    int PROTOCOL_VERSION = 1073742084;

    int DATA_VERSION = 4534;

    MajorMinorVersion RESOURCE_PACK_VERSION = new MajorMinorVersion(65, 0);

    MajorMinorVersion DATA_PACK_VERSION = new MajorMinorVersion(82, 0);
}
